// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/edit_profile/data/data_source_impl/edit_profile_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:flower_ecommerce/core/api/api_manager/api_manager.dart' as _i14;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/forget_password_request.dart'
    as _i17;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/reset_password_request.dart'
    as _i20;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/verify_request.dart'
    as _i18;
import 'package:flower_ecommerce/Features/auth/data/models/request/login_model_dto.dart'
    as _i19;
import 'package:flower_ecommerce/Features/auth/data/models/request/register_model_dto.dart'
    as _i16;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/forget_password_response.dart'
    as _i3;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/reset_password_response.dart'
    as _i6;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/verify_response.dart'
    as _i4;
import 'package:flower_ecommerce/Features/auth/data/models/response/login_response_dto.dart'
    as _i5;
import 'package:flower_ecommerce/Features/auth/data/models/response/register_response_dto.dart'
    as _i2;
import 'package:flower_ecommerce/Features/best_seller/data/model/best_seller_response.dart'
    as _i10;
import 'package:flower_ecommerce/Features/categories/data/models/response/all_categories.dart'
    as _i8;
import 'package:flower_ecommerce/Features/edit_profile/data/models/edit_profile.dart'
    as _i13;
import 'package:flower_ecommerce/Features/home/data/models/home_model.dart'
    as _i11;
import 'package:flower_ecommerce/Features/occasions/data/models/occasion_response/occasion_response.dart'
    as _i21;
import 'package:flower_ecommerce/Features/products/data/models/all_products.dart'
    as _i9;
import 'package:flower_ecommerce/Features/products_details/data/models/response/product_details_dto.dart'
    as _i7;
import 'package:flower_ecommerce/Features/profile/data/model/profile_response.dart'
    as _i23;
import 'package:flower_ecommerce/Features/profile_reset_password/data/model/change_password_request.dart'
    as _i22;
import 'package:flower_ecommerce/Features/profile_reset_password/data/model/change_password_response.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResponse_2 extends _i1.SmartFake
    implements _i4.VerifyResponse {
  _FakeVerifyResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponseDto_3 extends _i1.SmartFake
    implements _i5.LoginResponseDto {
  _FakeLoginResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductDetailsDto_5 extends _i1.SmartFake
    implements _i7.ProductDetailsDto {
  _FakeProductDetailsDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllCategories_6 extends _i1.SmartFake implements _i8.AllCategories {
  _FakeAllCategories_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllProducts_7 extends _i1.SmartFake implements _i9.AllProducts {
  _FakeAllProducts_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBestSellerResponse_8 extends _i1.SmartFake
    implements _i10.BestSellerResponse {
  _FakeBestSellerResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeModel_9 extends _i1.SmartFake implements _i11.HomeModel {
  _FakeHomeModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangePasswordResponse_10 extends _i1.SmartFake
    implements _i12.ChangePasswordResponse {
  _FakeChangePasswordResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEditProfile_11 extends _i1.SmartFake implements _i13.EditProfile {
  _FakeEditProfile_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i14.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i2.RegisterResponseDto> signUp(
          _i16.RegisterModelDto? registerModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [registerModelDto],
        ),
        returnValue: _i15.Future<_i2.RegisterResponseDto>.value(
            _FakeRegisterResponseDto_0(
          this,
          Invocation.method(
            #signUp,
            [registerModelDto],
          ),
        )),
      ) as _i15.Future<_i2.RegisterResponseDto>);

  @override
  _i15.Future<_i3.ForgetPasswordResponse> forgetPassword(
          _i17.ForgetPasswordRequest? requestEmail) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [requestEmail],
        ),
        returnValue: _i15.Future<_i3.ForgetPasswordResponse>.value(
            _FakeForgetPasswordResponse_1(
          this,
          Invocation.method(
            #forgetPassword,
            [requestEmail],
          ),
        )),
      ) as _i15.Future<_i3.ForgetPasswordResponse>);

  @override
  _i15.Future<_i4.VerifyResponse> verifyPassword(
          _i18.VerifyRequest? requestOtp) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [requestOtp],
        ),
        returnValue:
            _i15.Future<_i4.VerifyResponse>.value(_FakeVerifyResponse_2(
          this,
          Invocation.method(
            #verifyPassword,
            [requestOtp],
          ),
        )),
      ) as _i15.Future<_i4.VerifyResponse>);

  @override
  _i15.Future<_i5.LoginResponseDto> login(_i19.LoginModelDto? loginModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginModelDto],
        ),
        returnValue:
            _i15.Future<_i5.LoginResponseDto>.value(_FakeLoginResponseDto_3(
          this,
          Invocation.method(
            #login,
            [loginModelDto],
          ),
        )),
      ) as _i15.Future<_i5.LoginResponseDto>);

  @override
  _i15.Future<_i6.ResetPasswordResponse> resetPassword(
          _i20.ResetPasswordRequest? requestOtp) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [requestOtp],
        ),
        returnValue: _i15.Future<_i6.ResetPasswordResponse>.value(
            _FakeResetPasswordResponse_4(
          this,
          Invocation.method(
            #resetPassword,
            [requestOtp],
          ),
        )),
      ) as _i15.Future<_i6.ResetPasswordResponse>);

  @override
  _i15.Future<_i7.ProductDetailsDto> getProductDetails(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetails,
          [productId],
        ),
        returnValue:
            _i15.Future<_i7.ProductDetailsDto>.value(_FakeProductDetailsDto_5(
          this,
          Invocation.method(
            #getProductDetails,
            [productId],
          ),
        )),
      ) as _i15.Future<_i7.ProductDetailsDto>);

  @override
  _i15.Future<_i8.AllCategories> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i15.Future<_i8.AllCategories>.value(_FakeAllCategories_6(
          this,
          Invocation.method(
            #getAllCategories,
            [],
          ),
        )),
      ) as _i15.Future<_i8.AllCategories>);

  @override
  _i15.Future<_i9.AllProducts> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue: _i15.Future<_i9.AllProducts>.value(_FakeAllProducts_7(
          this,
          Invocation.method(
            #getAllProducts,
            [],
          ),
        )),
      ) as _i15.Future<_i9.AllProducts>);

  @override
  _i15.Future<_i10.BestSellerResponse> getBestSeller() => (super.noSuchMethod(
        Invocation.method(
          #getBestSeller,
          [],
        ),
        returnValue: _i15.Future<_i10.BestSellerResponse>.value(
            _FakeBestSellerResponse_8(
          this,
          Invocation.method(
            #getBestSeller,
            [],
          ),
        )),
      ) as _i15.Future<_i10.BestSellerResponse>);

  @override
  _i15.Future<_i11.HomeModel> getHomeData() => (super.noSuchMethod(
        Invocation.method(
          #getHomeData,
          [],
        ),
        returnValue: _i15.Future<_i11.HomeModel>.value(_FakeHomeModel_9(
          this,
          Invocation.method(
            #getHomeData,
            [],
          ),
        )),
      ) as _i15.Future<_i11.HomeModel>);

  @override
  _i15.Future<_i21.OccasionResponse?> getOccasions() => (super.noSuchMethod(
        Invocation.method(
          #getOccasions,
          [],
        ),
        returnValue: _i15.Future<_i21.OccasionResponse?>.value(),
      ) as _i15.Future<_i21.OccasionResponse?>);

  @override
  _i15.Future<_i12.ChangePasswordResponse> changePassword(
    _i22.ChangePasswordRequest? changePasswordRequest,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            changePasswordRequest,
            token,
          ],
        ),
        returnValue: _i15.Future<_i12.ChangePasswordResponse>.value(
            _FakeChangePasswordResponse_10(
          this,
          Invocation.method(
            #changePassword,
            [
              changePasswordRequest,
              token,
            ],
          ),
        )),
      ) as _i15.Future<_i12.ChangePasswordResponse>);

  @override
  _i15.Future<_i23.ProfileResponse?> getProfileData(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [token],
        ),
        returnValue: _i15.Future<_i23.ProfileResponse?>.value(),
      ) as _i15.Future<_i23.ProfileResponse?>);

  @override
  _i15.Future<_i13.EditProfile> editProfile(
    String? token,
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProfile,
          [
            token,
            firstName,
            lastName,
            email,
            phone,
          ],
        ),
        returnValue: _i15.Future<_i13.EditProfile>.value(_FakeEditProfile_11(
          this,
          Invocation.method(
            #editProfile,
            [
              token,
              firstName,
              lastName,
              email,
              phone,
            ],
          ),
        )),
      ) as _i15.Future<_i13.EditProfile>);
}
