// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce/test/Features/home/data/data_sources_impl/home_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flower_ecommerce/core/api/api_manager/api_manager.dart' as _i8;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/forget_password_request.dart'
    as _i11;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/reset_password_request.dart'
    as _i14;
import 'package:flower_ecommerce/Features/auth/data/models/request/forget_password_request/verify_request.dart'
    as _i12;
import 'package:flower_ecommerce/Features/auth/data/models/request/LoginModelDto.dart'
    as _i13;
import 'package:flower_ecommerce/Features/auth/data/models/request/RegisterModelDto.dart'
    as _i10;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/forget_password_response.dart'
    as _i3;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/reset_password_response.dart'
    as _i6;
import 'package:flower_ecommerce/Features/auth/data/models/response/forget_password_response/verify_response.dart'
    as _i4;
import 'package:flower_ecommerce/Features/auth/data/models/response/LoginResponseDto.dart'
    as _i5;
import 'package:flower_ecommerce/Features/auth/data/models/response/RegisterResponseDto.dart'
    as _i2;
import 'package:flower_ecommerce/Features/home/data/models/home_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeForgetPasswordResponse_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyResponse_2 extends _i1.SmartFake
    implements _i4.VerifyResponse {
  _FakeVerifyResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponseDto_3 extends _i1.SmartFake
    implements _i5.LoginResponseDto {
  _FakeLoginResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeModel_5 extends _i1.SmartFake implements _i7.HomeModel {
  _FakeHomeModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.RegisterResponseDto> signUp(
          _i10.RegisterModelDto? registerModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [registerModelDto],
        ),
        returnValue: _i9.Future<_i2.RegisterResponseDto>.value(
            _FakeRegisterResponseDto_0(
          this,
          Invocation.method(
            #signUp,
            [registerModelDto],
          ),
        )),
      ) as _i9.Future<_i2.RegisterResponseDto>);

  @override
  _i9.Future<_i3.ForgetPasswordResponse> forgetPassword(
          _i11.ForgetPasswordRequest? requestEmail) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [requestEmail],
        ),
        returnValue: _i9.Future<_i3.ForgetPasswordResponse>.value(
            _FakeForgetPasswordResponse_1(
          this,
          Invocation.method(
            #forgetPassword,
            [requestEmail],
          ),
        )),
      ) as _i9.Future<_i3.ForgetPasswordResponse>);

  @override
  _i9.Future<_i4.VerifyResponse> verifyPassword(
          _i12.VerifyRequest? requestOtp) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [requestOtp],
        ),
        returnValue: _i9.Future<_i4.VerifyResponse>.value(_FakeVerifyResponse_2(
          this,
          Invocation.method(
            #verifyPassword,
            [requestOtp],
          ),
        )),
      ) as _i9.Future<_i4.VerifyResponse>);

  @override
  _i9.Future<_i5.LoginResponseDto> login(_i13.LoginModelDto? loginModelDto) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginModelDto],
        ),
        returnValue:
            _i9.Future<_i5.LoginResponseDto>.value(_FakeLoginResponseDto_3(
          this,
          Invocation.method(
            #login,
            [loginModelDto],
          ),
        )),
      ) as _i9.Future<_i5.LoginResponseDto>);

  @override
  _i9.Future<_i6.ResetPasswordResponse> resetPassword(
          _i14.ResetPasswordRequest? requestOtp) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [requestOtp],
        ),
        returnValue: _i9.Future<_i6.ResetPasswordResponse>.value(
            _FakeResetPasswordResponse_4(
          this,
          Invocation.method(
            #resetPassword,
            [requestOtp],
          ),
        )),
      ) as _i9.Future<_i6.ResetPasswordResponse>);

  @override
  _i9.Future<_i7.HomeModel> getHomeData() => (super.noSuchMethod(
        Invocation.method(
          #getHomeData,
          [],
        ),
        returnValue: _i9.Future<_i7.HomeModel>.value(_FakeHomeModel_5(
          this,
          Invocation.method(
            #getHomeData,
            [],
          ),
        )),
      ) as _i9.Future<_i7.HomeModel>);
}
