name: Dart Linting

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SDart/Flutter Package Analyzer
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: dart pub get

      - name: Run Dart analysis
        run: dart analyze
