name: Dart Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.5.4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.24.5

      - name: Install dependencies
        run: flutter pub get

      - name: Run Dart Lint
        run: dart analyze
